language: python
python:
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
#yeah, thanks GitHub now I know how to make comments. Anyways, this below is for testing against the latest version of Python for iOS.
# command to run tests
script: nosetests
